services:
  be:
    container_name: ayunee_be
    build:
      context: ./be
      dockerfile: Dockerfile.dev
    volumes:
      - ./be:/app
    networks:
      - ayunee

  proxy:
    container_name: ayunee_proxy
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    environment:
      # CLIENT_PORT: 3000
      API_PORT: 8080
    ports: 
      - 80:80
    networks:
      - ayunee
    depends_on:
      - be

networks:
  ayunee:
    # driver: bridge