FROM node:18-alpine

WORKDIR /app

RUN addgroup -S appgroup && adduser -S app -G appgroup
COPY --chown=app:app package*.json ./
RUN npm install

COPY --chown=app:app . ./

RUN npx prisma generate 

USER app

CMD ["npm", "run", "dev"]